module.exports = [
  require('./CheckCommonsLoad')(),
  require('./CheckCommonsLoadFromTemplate')(),
  require('./CheckCommonsShowItems')(),
  require('./CheckCommonsTemplate')(),
  require('./CheckCommonsTemplateToWikidata')(),
  require('./CheckCommonsWikidataInfobox')(),
  require('./CheckWikidataLoadViaRef')(),
  require('./CheckWikidataShow')(),
  require('./CheckWikidataCoords')(),
  require('./CheckWikidataImage')(),
  require('./CheckWikidataIsA')(),
  require('./CheckWikidataLoadFromCommons')(),
  require('./CheckWikidataRecommendations')(),
  require('./CheckWikipediaListe')(),
  require('./CheckOsmLoadFromRefOrWikidata')(),
  require('./CheckOsmLoadFromWikidata')(),
  require('./CheckOsmLoadSimilar')()
]
